# Generated by Django 4.2 on 2023-04-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=10, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndexPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_price", models.FloatField()),
                ("high_price", models.FloatField()),
                ("low_price", models.FloatField()),
                ("close_price", models.FloatField()),
                ("adjusted_close_price", models.FloatField()),
                ("volume", models.IntegerField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stock_data.ticker",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="indexprice",
            constraint=models.UniqueConstraint(
                fields=("ticker", "date"), name="unique_date"
            ),
        ),
    ]
